function Flag_Custom() {
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.NAME,"CHARA");
	if(global.hardmode=true)
		Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.NAME,"Frisk");
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.LV,20);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.EXP,0);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP_MAX,99);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.HP,99);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+1,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+2,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+3,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+4,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+5,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+6,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM+7,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_WEAPON,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ITEM_ARMOR,-1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.ATK,46);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.DEF,14);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.SPD,2);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.KILLS,109)
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.INV,1);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.TP_COOLDOWN,40);
	Flag_Set(FLAG_TYPE.STATIC,FLAG_STATIC.BATTLE_MENU_FIGHT_OBJ,battle_menu_fight_trueknife);

	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.BATTLE_ROOM_RETURN,-1);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_LANDMARK,noone);
	Flag_Set(FLAG_TYPE.TEMP,FLAG_TEMP.TRIGGER_WARP_DIR,-1);

	Item_SetWeapon(item_trueknife);
	Item_SetArmor(item_truelocket);
	Player_SetAtkItem(99);
	Player_SetDefItem(99);
	Phone_Set(0,phone_toriel);
	Item_Set(0,item_pie);
	Item_Set(1,item_steak);
	Item_Set(2,item_hero);
	Item_Set(3,item_hero);
	Item_Set(4,item_hero);
	Item_Set(5,item_snow);
	Item_Set(6,item_snow);
	Item_Set(7,item_snow);
	global.itemstyle_set = 1
	global.itemstyle = 0
	global.serious = 1
}
