image_xscale=(width/2);
image_angle=angle;

if(!bounce_x){
	x+=move_x;
}else{
	repeat(abs(move_x)*10){
		if(!place_meeting(x+sign(move_x)*0.1,y,block)){
			x+=sign(move_x)*0.1;
		}else{
			move_x=-move_x;
			break;
		}
	}
}
if(!bounce_y){
	y+=move_y;
}else{
	repeat(abs(move_y)*10){
		if(!place_meeting(x,y+sign(move_y)*0.1,block)){
			y+=sign(move_y)*0.1;
		}else{
			move_y=-move_y;
			break;
		}
	}
}

if(Battle_GetState()!=BATTLE_STATE.IN_TURN){
	instance_destroy();
}