var xpos = floor(random_range(160,530))
var inst=instance_create_depth(xpos,0,0,battle_bullet_gb);
inst.x_target=xpos
inst.y_target=battle_board.y-battle_board.up-100;
inst.angle_start=irandom_range(0, 359);
inst.angle_target=-90;
inst.type=0;
inst.scale_y=2;
inst.scale_x=2;
inst.time_beam_end_delay=15;
inst.time_release_delay=10;
alarm[5] = 120